### ISSUE TITLE
Importing v1 files doesn't parse some character correctly

### ISSUE THREAD

**Issue by whipflash191** [maforget/CRDataManager#2]
Hi, I'm just getting back into comics and working on updating my install. I tried install your latest version of Data Manager but encounter this error when trying to use it 
![image](https://user-images.githubusercontent.com/22025166/161222065-fb3e2968-b8a5-429d-bab2-4a3bb14d7a80.png)

**Comment by maforget** [comment]
Can you post your dataman.dat file?

**Comment by whipflash191** [comment]
[data manger.zip](https://github.com/maforget/CRDataManager/files/8400121/data.manger.zip)
This should be it, looks like a an compatibility issue with .dat created in an older version of the plugin. I started from scratch with a completely fresh .dat file and it's works perfectly now.

**Comment by maforget** [comment]
One of the fix for this version is to be able to load v1 dat files like yours. So it should still open it.

The problem comes from using an @ in a rule name. You are using `Army @ Love`. The @ char is special and used for comments.

So here is the fixed v1 (just renamed `Army @ Love` to `Army at Love` in the rule name. And the v2 dat file.
[data manager v1 Fix + v2.zip](https://github.com/maforget/CRDataManager/files/8400301/data.manager.v1.Fix.%2B.v2.zip)

**Comment by maforget** [comment]
I changed the behavior of the v1 parsing to prevent these kind of problems. https://github.com/maforget/CRDataManagerGUI/commit/915417eef00ba0c8c4cdbc0e13c77b5159b5dca9

You can download the new GUI here (version is r804). 
https://github.com/maforget/CRDataManager/raw/e6b839eaffa6fca4239815388abb9d40a7b72c9c/crdmgui.exe
