### ISSUE TITLE
 Tags and Genre:  ContainAnyOf  &  NotContainAnyOf  not working

### ISSUE THREAD

**Issue by 5h4k3** [maforget/CRDataManager#5]
Hello !

This doesn't seem to be the case for all multi-value fields. I would even say that the other fields seem to work correctly, as far as I remember. But **Tags** and **Genre** don't like the use of : **ContainAnyOf**  &  **NotContainAnyOf** …

Since "IsAny…", "StartWith…", etc are not available it's a bit annoying but once you know it, the workaround is quite easy. 
You just have to copy the values ​​into an unused field like "BookNotes" and there, because these two elements are working, it becomes possible to make comparisons. Quite like when I want to play with RegEx in fields that don't support it…

So this Issue is therefore more for informational purposes than a real problem awaiting a solution…

Anyway, thanks again for all that you done for us ! 
Bonne continuation !

**Comment by 5h4k3** [comment]
Il y a autre chose, je ne sais pas quoi, j'arrive plus à reproduire le "bug" alors qu'il m'a emmerdé pendant plusieurs heures. Dsl je clos en attendant d'être certain.

Edit: Bon faut pas que je tente les règles compliquées au pied du lit. Le problème était tout simplement entre le clavier et le fauteuil comme souvent... Le résultat d'une règle que j'aurais du placer à la fin d'une longue liste car son résultat rentrait du coup dans les conditions d'une autre qui l'a re-modifiait… J'ai dû faire une autre connerie du genre les fois précédentes. J'ai testé les caractères bizarres et compagnie, ça fonctionne… Pfff

J'ai tout de même parfois le champ des valeurs qu'on rentre (à droite) qui bug/disparait puis prends la valeur de la ligne du dessous avec les Contain/ContainAll et même en cliquant dedans, si l'on veut modifier la valeur, il faut jouer avec le choix déroulant ou tout effacer et retaper. Mais ça semble fonctionner, je crois.

Enfin bref, c'est plein de petits trucs qui font que je m’emmêle un peu les crayons entre ça et quelques bricoles dans CR...

Le bon coté c'est que vu l'heure, tu n'auras pas eu le temps de voir et de te pauser la question pour mes bêtises !

Bonne journée.
Slt. (Flemme de réécrire en anglais pour ce que ça apportera…)

**Comment by maforget** [comment]
Je vais répondre en anglais pour ceux qui voudrais si référer.

There really isn't any reason that IsAnyOf & StartWithAnyOf can't work with multi fields. I've implemented these changes in version 2.07.05.824, that should be available in the [nightly](https://github.com/maforget/CRDataManager/releases/tag/nightly) section.

For the textbox not really updating, it can happen. I've patched a lot and still do when I find them. It happens depending on the Parameter (Is, Contains, Calc, RegexReplace, SetValue, etc.) or type of field (numeric, multi, regex, date, manga, language). etc. The main reason is that all the different gui elements for these different types are all on top of each other, but the main string text box is still the one that stores all the important data. 

Sometimes the previous field fills the main text box but when changing to the new one the gui isn't correctly updated (missing instructions for this specific combination), so you get the wrong value. It's just that a certain type of field isn't filling the main text box (so it's either empty or using the previous value) or the main text box is filled but the current one based on the type isn't.

These little problem can be annoying, which is why I started fixing this plugin, so please open an issue for these. But to fix I need specific steps to reproduce the problem. I would need the exact order of field/rules/action/modifier. Like the first field/rules/action/modifier selected then the modifier/field changed after. Or you clicked on this combination of field/rules/action/modifier and then this other one. Sharing exact rules would help also, just share the XML in the Text bar at the top.

**Comment by 5h4k3** [comment]
Understood!
I will look more carefully at these bug when I will catch one. And I will report them correctly with all the info. If multiple, I will export and then upload the rules here…
Again, sorry…
See u!
